<!-- CODE HTML DU FORMULAIRE --> 
<form action="/add-task" method="POST">
    <fieldset>
        <legend>Ajout d'une nouvelle tâche</legend>
        <div class="mb-3 form-group">
            <label for="title">Titre</label>
            <input value="<?=htmlspecialchars($title);?>" type="text" name="title" class="form-control" id="title" placeholder="Titre de la tâche">
            <?php if (isset($errors['title'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['title']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3 form-group">
            <label for="description">Description</label>
            <textarea rows="3" name="description" class="form-control" id="description"><?=htmlspecialchars($description);?></textarea>
            <?php if (isset($errors['description'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['description']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3 form-group">
            <label for="deadline">Deadline</label>
            <input value="<?=htmlspecialchars($deadline);?>" type="date" class="form-control" name="deadline" id="deadline">
            <?php if (isset($errors['deadline'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['deadline']);?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3 form-group">
            <label for="priority">Priorité</label>
            <select name="priority" class="form-control" id="priority">
                <?php foreach ($priorities as $p): ?>
                    <?php $selected = $priority == $p['id'] ? 'selected' : ''; ?>
                    <option <?=$selected;?> value="<?=intval($p['id'])?>"><?=htmlspecialchars($p['label'])?></option>
                <?php endforeach; ?>
            </select>
            <?php if (isset($errors['priority'])): ?>
                <p class="mt-3 alert alert-danger"><?=htmlspecialchars($errors['priority']);?></p>
            <?php endif; ?>
        </div>
        <div class="form-group">
            <input class="btn btn-primary mt-4" type="submit" value="Enregistrer">
        </div>
    </fieldset>
</form>
                      