<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>

<body>
    <section class="vh-100 gradient-custom-2">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 col-xl-10">
                    <div class="mask-custom">
                        <div class="card-body p-4 text-white">

                            <nav>
                                <a href="/" class="btn btn-primary mx-1">
                                    <i class="fa-solid fa-home"></i>
                                    Accueil
                                </a>

                                <!-- MENU EN MODE CONNECTE -->
                                <?php if (isConnected()): ?>
                                    <a href="/add-task" class="btn btn-primary mx-1">
                                        <i class="fa-solid fa-plus"></i>
                                        Nouvelle tâche
                                    </a>
                                    <a href="/logout" class="btn btn-primary mx-1">
                                        <i class="fa-solid fa-right-from-bracket"></i>
                                        Déconnexion
                                    </a>
                                <?php else: ?>
                                    <!-- MENU EN MODE NON CONNECTE -->
                                    <a href="/signup" class="btn btn-primary mx-1">
                                        <i class="fa-solid fa-user-plus"></i>
                                        Créer un compte
                                    </a>
                                    <a href="/login" class="btn btn-primary mx-1">
                                        <i class="fa-solid fa-right-to-bracket"></i>
                                        Connexion
                                    </a>
                                <?php endif; ?>
                            </nav>

                            <!-- inclusion du template spécifique à la page affichée -->
                            <?php include '../templates/' . $template . '.phtml';?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>
